theme: jekyll-theme-merlot

# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: The Booter

# Short description (goes below the title; it will also be used in the RSS feed)
description: This is a placeholder page for The Booter.

# Your name, as you want it to appear underneath each post and in the footer
author: Ricardo Aravena

# Your email if you want it to be linked on the contact page
author_email: raravena@serverbooter.com

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: https://booter.serverbooter.com/

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
markdown: rdiscount

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty
